sudo: required
language: c++
services:
- docker

before_install:
- docker pull trusch/susi-builder:stable

script:
- docker run -v $(pwd):/src trusch/susi-builder:stable

deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: paehviEiDauFBNQK7pzveie0Ynv7bXKoafCso8dqV4WpdUjaFpB9waDJBGd1suedEGF/YW7VjQVQ1wi4d3f7AJ/vX8kgsTLYdRSLWuWziBNuRBEukGthGgGhbwxdOyVIXpiqkrF8sB2BsB3RBTJtnv/V21JaOy3EUF0ybre7wCN5Q2YuR2Eqtc+WLYUr3BPMzia43S9ChiRcjow+9AaH71ACnqc01L41+NAGMb6dinBPjB3w3VTC9q269nbh4H72lsgCcOMjlDQKi+rl5+YwApfwVuKgLd0qOKNXjyBKisk1S7OafwCrlXV2EXC6RxtY0TJEemUBnh145F6hm5i3/NaKRURDj1L54FLbAki11SzMXRTp7S962Db1o0JWXxbx3kV1dEWrVdOfIofVKP5T6CXWZ0R584+vXps12DVOlXyhCMhrEvvjWLRagbtcF4ZehHY4eizXqDiJYxFpFDb6veTkcAj3nOjOmdSVAkQLgkPgAcDwwyF5wWlMdsQxaod4rjHGOwN6e8oniRpP+dnFMivvtwxbblLtw7Gu9X7SbHxdreGsZPyh8XOGBwjbOmRODjErX48hYeGAGMWUJZUGpx5S86RVWr7X5S6INm1rZZSy1TV6lsH/26KT969Jxd2VXguCDbetrxeuZhTIgSgaK///eAODUYPVX8nuiagLh2M=
  file: "build/susi-core-0.2.0-Linux.deb"
