sudo: required
language: c++
services:
  - docker

before_install:
  - docker build -t susi/builder .
  - docker run -v $(pwd):/src susi/builder /bin/bash -c ' \

script:
  - docker run -v $(pwd):/src susi/builder /bin/bash -c ' \
    cd /src/submodules/libbson; \
    cmake .; \
    make -j8; \
    make install; \
    cd /src/submodules/libsusi; \
    cmake .; \
    make -j8; \
    make install; \
    cd /src/build; \
    cmake ..; \
    make -j8;
